# Generated by Django 5.1.2 on 2024-10-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=1000)),
                ('interest', models.CharField(max_length=1000)),
                ('wanted', models.CharField(max_length=1000)),
                ('future', models.CharField(max_length=1000)),
            ],
        ),
    ]
